name: ZAP DAST Scan on Juice Shop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  zap_scan:
    name: ZAP Scan
    runs-on: ubuntu-latest

    services:
      juice-shop:
        image: bkimminich/juice-shop:v15.3.0
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl -s http://localhost:3000" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for Juice Shop to become available
        run: |
          echo "Waiting for Juice Shop to start on port 3000..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              break
            fi
            echo "Still waiting..."
            sleep 5
          done

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          fail_action: false  # Do not fail the workflow on alerts; set to true if you want to block PRs
